### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by sebastic** [libogdi/ogdi#13]
The Debian package uploads of OGDI 4.0.0 were rejected because of license issues.

It was initially rejected because the terms in `license.terms` for `ecshash.c` were not included in the copyright file (just like in the `LICENSE` file):

> one of our hardworking trainees found:
>>  License information for ogdi/c-api/ecshash.c needs to be included in
>>  d/copyright, rather than referenced. 
> 
> So what does license.terms contain?

See: [ogdi-dfsg_4.0.0+ds-1~exp1_amd64.changes REJECTED](https://alioth-lists.debian.net/pipermail/pkg-grass-devel/2019-April/076887.html)

The `ogdi/c-api` directory does not contain the `license.terms` file, it is located in [`include/win32/compat/license.terms`](https://github.com/libogdi/ogdi/blob/master/include/win32/compat/license.terms), which contains the clause:
> RESTRICTED RIGHTS: Use, duplication or disclosure by the government
is subject to the restrictions as set forth in subparagraph (c) (1) (ii)
of the Rights in Technical Data and Computer Software Clause as DFARS
252.227-7013 and FAR 52.227-19.

This is incompatible with the "No Discrimination Against Fields of Endeavor" paragraph of the DFSG & OSD. This caused the subsequent rejection:

> The following note was added by an ftpmaster-in-training. It will appear to be
"From" me as I am the one actioning it.
> 
> (snip)
> 
> REJECT
> 
> [This note DOES apply to the ~exp2 upload!]
> 
> The RESTRICTED RIGHTS section of `License: ecshash` looks to violate
> DFSG clauses 5 and/or 6, if that paragraph is indeed part of the
> license.  (If it's just noting a legal requirement that applies to the
> government in all cases, the license might be DFSG-free; in that case,
> it shouldn't be in d/copyright.)
> 
> I am not sure that the license of ogdi/c-api/ecsregex.c actually
> permits derivative works.
> 
> The license of include/win32/rpc/auth.h, external/rpc_win32/ is not
> DFSG-free -- it has weird restrictions on distribution.
> 
> License of d/patches/hurd not given.
> 
> I did not look through all of the upstream source, given the severity
> of the above issues. 

See: [ogdi-dfsg_4.0.0+ds-1~exp4_amd64.changes REJECTED](https://alioth-lists.debian.net/pipermail/pkg-grass-devel/2019-April/077116.html)

The license terms for `ecsregex.c` do allow modification as long as these are clearly stated:
>  Permission is granted to anyone to use this software for any
>  purpose on any computer system, and to redistribute it freely,
>  subject to the following restrictions:
> 
>  1. The author is not responsible for the consequences of use of
>     this software, no matter how awful, even if they arise
>     from defects in it.
> 
>  2. The origin of this software must not be misrepresented, either
>     by explicit claim or by omission.
> 
>  3. Altered versions must be plainly marked as such, and must not
>     be misrepresented as being the original software.

The win32 sources can be excluded from the repacked upstream tarball, but that will also remove the `license.terms` file (whose content should be moved to the `LICENSE` file).

These issues need to be resolved to get OGDI 4.0.0 into Debian, and be able to keep 3.2 for which the license & copyright review has apparently not been as thorough.

**Comment by sebastic** [comment]
Many thanks for the quick response!

Hopefully OGDI 4.1.0 will be accepted into the Debian archive soon.

**Comment by gdt** [comment]
I think this is a misinterpretation of DoD contracting terms, and there is no field of endeavor discrimination.

When the US government pays for software to be developed, the standard terms are that they receive Unlimited Rights, which is a broad license under copyright law, enabling them to do anything controlled by copyright law.  This is essentially a customer hiring a consultant getting very favorable terms to the software the consultant writes while charging hours to that customer.

For software developed partially at private expense, there are notions of "Government-Purpose Rights" and "Restricted Rights", which are more limited grants of the special customer license.

It is not unusual for a contractor, which holds copyright to works created by their employees under a government contract via the work-for-hire doctrine, to release that software under an open source license.

None of this Restricted Rights prevents the government from exercising the same rights that any other party has under an open source license.  It's merely about the special rights they would normally have gotten not being as expansive.  So if there is a Restricted Rights legend and GPL, then the government can follow the GPL.  If the code was written under a contract with no special terms, and the contractor chose to grant permission under the GPL to everyone, then normally the government would have a separate, additional license to do almost anything in addition to the GPL.

It is unfortunate that the "Use or duplication by the government is subject to restrictions".  I am 99% sure that this applies to the normal customer license that is in the acquisition regulations, and does not apply to the government following the BSD-like terms available to everyone.   I have never, not even once, seen a license with that kind of interpretation using these words.

I'm of course not a lawyer, but I have read a number of US government contracts with these kinds of terms.

**Comment by gdt** [comment]
And the Restricted Rights text is ritual.  It is essentially always written just like that.
