### ISSUE TITLE
Failed to install with "make install"

### ISSUE THREAD

**Issue by jiapei100** [libogdi/ogdi#8]
The Error:

```console
➜  ogdi git:(master) ✗ sudo make install
makefile:20: /config/common.mak: No such file or directory
make: *** No rule to make target '/config/common.mak'.  Stop.
```

**Comment by rouault** [comment]
See https://github.com/libogdi/ogdi/blob/master/README for the build procedure

**Comment by jiapei100** [comment]
@rouault 
I strictly followed this README, but still failed with the above error message.
I'm using **zsh**. Does that cause this issue?

Cheers
